[build]
builder = "dockerfile"
dockerfilePath = "apps/backoffice/Dockerfile"

[deploy]
startCommand = "bun run apps/backoffice/build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
